# Docker Compose configuration with secrets management
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up
version: '3.8'

services:
  postgres:
    secrets:
      - db_password
      - db_user
    environment:
      POSTGRES_DB: ${DB_DATABASE:-lifebox}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

  lifebox-api:
    secrets:
      - jwt_secret
      - db_password
      - smtp_password
      - twilio_auth_token
    environment:
      # Use secrets files instead of environment variables
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      DB_PASSWORD_FILE: /run/secrets/db_password
      SMTP_PASS_FILE: /run/secrets/smtp_password
      TWILIO_AUTH_TOKEN_FILE: /run/secrets/twilio_auth_token

  lifebox-mqtt:
    secrets:
      - mqtt_password
      - api_token
    environment:
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      API_TOKEN_FILE: /run/secrets/api_token

secrets:
  db_user:
    external: true
    name: lifebox_db_user
  db_password:
    external: true
    name: lifebox_db_password
  jwt_secret:
    external: true
    name: lifebox_jwt_secret
  smtp_password:
    external: true
    name: lifebox_smtp_password
  twilio_auth_token:
    external: true
    name: lifebox_twilio_token
  mqtt_password:
    external: true
    name: lifebox_mqtt_password
  api_token:
    external: true
    name: lifebox_api_token